// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tpl-x/httpl/internal/config"
	"github.com/tpl-x/httpl/internal/logger"
)

// Injectors from wire.go:

// wireApp init for builder backend
func wireApp(conf *config.AppConfig) *app {
	logConfig := &conf.Log
	slogLogger := logger.NewSlogLogger(logConfig)
	mainApp := newApp(conf, slogLogger)
	return mainApp
}
